export const EMAIL_TYPES = {
  VERIFICATION_CODE: "VERIFICATION_CODE",
  VERIFICATION_LINK: "VERIFICATION_LINK",
  PASSWORD_RESET: "PASSWORD_RESET",
  RESERVATION_STATUS: "RESERVATION_STATUS",
  RESERVATION_COMPLETED: "RESERVATION_COMPLETED",
  RESERVATION_CREATED: "RESERVATION_CREATED",
};

